In [33]:
import os
import tensorflow as tf
import numpy as np
import random
import time
import matplotlib.pyplot as plt
import pickle
from matplotlib.backends.backend_pdf import PdfPages
from hyperdash import monitor_cell
from hyperdash import Experiment
import inspect, re
import re
import traceback

In [8]:
RFace =np.array([['R1','R2','R3'],['R4','R5','R6'],['R7','R8','R9']])
BFace =np.array([['G1','G2','G3'],['G4','G5','G6'],['G7','G8','G9']])
LFace =np.array([['O1','O2','O3'],['O4','O5','O6'],['O7','O8','O9']])
DFace =np.array([['W1','W2','W3'],['W4','W5','W6'],['W7','W8','W9']])
FFace =np.array([['B1','B2','B3'],['B4','B5','B6'],['B7','B8','B9']])
UFace =np.array([['Y1','Y2','Y3'],['Y4','Y5','Y6'],['Y7','Y8','Y9']])

In [48]:
def func(var):
    stack = traceback.extract_stack()
    filename, lineno, function_name, code = stack[-2]
    vars_name = re.compile(r'\((.*?)\).*$').search(code).groups()[0]
    vars_name = vars_name.split("'")
    return vars_name

In [15]:
def cube():
    cube = {
        'Front'  : np.array([['B1','B2','B3'],['B4','B5','B6'],['B7','B8','B9']]),
        'Back'   : np.array([['G1','G2','G3'],['G4','G5','G6'],['G7','G8','G9']]),
        'Left'   : np.array([['O1','O2','O3'],['O4','O5','O6'],['O7','O8','O9']]),
        'Right'  : np.array([['R1','R2','R3'],['R4','R5','R6'],['R7','R8','R9']]),
        'Down'   : np.array([['W1','W2','W3'],['W4','W5','W6'],['W7','W8','W9']]),
        'Up'     : np.array([['Y1','Y2','Y3'],['Y4','Y5','Y6'],['Y7','Y8','Y9']]),
    }
    return cube
    

In [44]:
c = cube()
x = cube()
print(c['Front'])
print(x['Back'])
name = func(x['Back'])
print(name)

[['B1' 'B2' 'B3']
 ['B4' 'B5' 'B6']
 ['B7' 'B8' 'B9']]
[['G1' 'G2' 'G3']
 ['G4' 'G5' 'G6']
 ['G7' 'G8' 'G9']]
Back


In [21]:
def transpose(x):
    out = np.zeros([0,len(x)])
    print(out)

In [65]:
def Rotation(face):
    stack = traceback.extract_stack()
    filename, lineno, function_name, code = stack[-2]
    vars_name = re.compile(r'\((.*?)\).*$').search(code).groups()[0]
    vars_name = vars_name.split("'")
    rotFace = vars_name[1]
    tempFace = np.zeros([5,5])
    if (rotFace == 'Front'):
        print(rotFace)
    elif (rotFace == 'Back'):
        print(rotFace)
    elif (rotFace == 'Left'):
        print(rotFace)
    elif (rotFace == 'Right'):
        print(rotFace)
    elif (rotFace == 'Up'):
        print(rotFace)
    elif (rotFace == 'Down'):
        print(rotFace)
        
    print(tempFace)

In [66]:
Rotation(x['Front'])

Front
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
